config/routes.rb
Rails.application.routes.draw do
  resources :leave_applications
  resources :invites
  resources :instalments  do
    collection do
      get 'get_instalments'
    end
  end

  resources :documents
  resources :events
  resources :projects
  resources :salary_transactions
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :salaries
  resources :user_profiles
  resources :statuses
  resources :designations
  resources :roles
  devise_for :users
  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :hr do
    collection do
      get 'users'
      get 'get_user_profile'
      post 'invite'
    end
  end

  resources :finance do
    collection do
      get 'salaries'
      get 'check_probation'
      get 'update_probation'
      get 'get_current_salary'
      get 'pay_salary'
    end
  end


  get 'welcome/public/:id', to: 'welcome#public_profile', as: 'public'
  get 'welcome/public_project/:id', to: 'welcome#public_project', as: 'public_project'




end

app/models/designation.rb
class Designation < ApplicationRecord
end

app/controllers/designations_controller.rb
class DesignationsController < ApplicationController

  before_action :authenticate_user!

  before_action :authorize_d_hr, only: [:index , :show ,:new , :edit , :create , :update , :destroy]

  before_action :set_designation, only: [:show, :edit, :update, :destroy]

  # GET /designations
  # GET /designations.json
  def index
    @designations = Designation.all
  end

  # GET /designations/1
  # GET /designations/1.json
  def show
  end

  # GET /designations/new
  def new
    @designation = Designation.new
  end

  # GET /designations/1/edit
  def edit
  end

  # POST /designations
  # POST /designations.json
  def create
    @designation = Designation.new(designation_params)

    respond_to do |format|
      if @designation.save
        format.html { redirect_to @designation, notice: 'Designation was successfully created.' }
        format.json { render :show, status: :created, location: @designation }
      else
        format.html { render :new }
        format.json { render json: @designation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /designations/1
  # PATCH/PUT /designations/1.json
  def update
    respond_to do |format|
      if @designation.update(designation_params)
        format.html { redirect_to @designation, notice: 'Designation was successfully updated.' }
        format.json { render :show, status: :ok, location: @designation }
      else
        format.html { render :edit }
        format.json { render json: @designation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /designations/1
  # DELETE /designations/1.json
  def destroy
    @designation.destroy
    respond_to do |format|
      format.html { redirect_to designations_url, notice: 'Designation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_designation
      @designation = Designation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def designation_params
      params.require(:designation).permit(:title, :description)
    end
end

app/helpers/designations_helper.rb
module DesignationsHelper
end

app/views/designations/_form.html.erb
<%= form_for(designation) do |f| %>
  <% if designation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(designation.errors.count, "error") %> prohibited this designation from being saved:</h2>

      <ul>
      <% designation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description , class: 'form-control'%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/designations/edit.html.erb
<div class="container">
  <div class=" jumbotron">
    <div>Editing Designation</div>

    <%= render 'form', designation: @designation %>

    <%= link_to 'Show', @designation %> |
    <%= link_to 'Back', designations_path %>
  </div>
</div>

app/views/designations/index.html.erb
<div class="container">
  <div class=" jumbotron">
    <div class="">
      Designations
        <%= link_to 'New Designation', new_designation_path , class:'btn btn-default right'%>
    </div>
    <br>
    <table class="table  table-striped table-hover table-condensed">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @designations.each do |designation| %>
          <tr>
            <td><%= designation.title %></td>
            <td><%= designation.description %></td>
            <td><%= link_to 'Show', designation %></td>
            <td><%= link_to 'Edit', edit_designation_path(designation) %></td>
            <td><%= link_to 'Destroy', designation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/designations/new.html.erb
<div class="container">
  <div class=" jumbotron">
    <div>New Designation</div>

    <%= render 'form', designation: @designation %>

    <%= link_to 'Back', designations_path %>
  </div>
</div>

app/views/designations/show.html.erb
<div class="container">
  <div class=" jumbotron">
    <p>
      <strong>Title:</strong>
      <%= @designation.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @designation.description %>
    </p>

    <%= link_to 'Edit', edit_designation_path(@designation) %> |
    <%= link_to 'Back', designations_path %>
  </div>
</div>