config/routes.rb
Rails.application.routes.draw do
  resources :leave_applications
  resources :invites
  resources :instalments  do
    collection do
      get 'get_instalments'
    end
  end

  resources :documents
  resources :events
  resources :projects
  resources :salary_transactions
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :salaries
  resources :user_profiles
  resources :statuses
  resources :designations
  resources :roles
  devise_for :users
  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :hr do
    collection do
      get 'users'
      get 'get_user_profile'
      post 'invite'
    end
  end

  resources :finance do
    collection do
      get 'salaries'
      get 'check_probation'
      get 'update_probation'
      get 'get_current_salary'
      get 'pay_salary'
    end
  end


  get 'welcome/public/:id', to: 'welcome#public_profile', as: 'public'
  get 'welcome/public_project/:id', to: 'welcome#public_project', as: 'public_project'




end

app/models/salary.rb
class Salary < ApplicationRecord
  belongs_to :user
end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_d_hr, only: [:index , :show ,:new , :edit , :create , :update , :destroy]

  before_action :set_salary, only: [:show, :edit, :update, :destroy]

  # GET /salaries
  # GET /salaries.json
  def index
    @salaries = Salary.all
  end

  # GET /salaries/1
  # GET /salaries/1.json
  def show
  end

  # GET /salaries/new
  def new
    @salary = Salary.new
  end

  # GET /salaries/1/edit
  def edit
  end

  # POST /salaries
  # POST /salaries.json
  def create
    
    @salary = Salary.new(salary_params)

    if  salary_params[:prov_period].to_i > 0
      user_profile = UserProfile.where(user_id: salary_params[:user_id]).first
      user_profile.probation = true
      user_profile.save!
    end

    respond_to do |format|
      if @salary.save
        format.html { redirect_to @salary, notice: 'Salary was successfully created.' }
        format.json { render :show, status: :created, location: @salary }
      else
        format.html { render :new }
        format.json { render json: @salary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salaries/1
  # PATCH/PUT /salaries/1.json
  def update
    respond_to do |format|
      if @salary.update(salary_params)
        format.html { redirect_to @salary, notice: 'Salary was successfully updated.' }
        format.json { render :show, status: :ok, location: @salary }
      else
        format.html { render :edit }
        format.json { render json: @salary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salaries/1
  # DELETE /salaries/1.json
  def destroy
    @salary.destroy
    respond_to do |format|
      format.html { redirect_to salaries_url, notice: 'Salary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salary
      @salary = Salary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salary_params
      params.require(:salary).permit(:user_id, :amount, :initial_amount_per_month, :prov_period)
    end
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/views/salaries/_edit_form.html.erb
<%= form_for(salary) do |f| %>
  <% if salary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(salary.errors.count, "error") %> prohibited this salary from being saved:</h2>

      <ul>
      <% salary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'Employee Names' %>
    <%= f.select :user_id, options_for_select(User.all.collect { |c| [c.name, c.id] }, salary.user_id), { prompt: 'Select User' }, class: 'form-control' , :required => true , disabled: true %>
  </div>

  <div class="">
    <div class="form-group col-sm-4">
      <%= f.label 'Salary in Lakh Per Annum' %>
      <%= f.text_field :amount , class: 'form-control' %>
    </div>

    <div class="form-group col-sm-4">
      <%= f.label :initial_amount_per_month %>
      <%= f.text_field :initial_amount_per_month ,  class: 'form-control' %>
    </div>

    <div class="form-group col-sm-4">
      <%= f.label 'Provesional period' %>
      <%= f.number_field :prov_period,  class: 'form-control' %>
    </div>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/salaries/_form.html.erb
<%= form_for(salary) do |f| %>
  <% if salary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(salary.errors.count, "error") %> prohibited this salary from being saved:</h2>

      <ul>
      <% salary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'New Employees' %>
    <%= f.select :user_id, options_for_select(User.where.not(:id => Salary.select(:user_id).map(&:user_id)).collect { |c| [c.name, c.id] }, salary.user_id), { prompt: 'Select User' }, class: 'form-control' , :required => true %>
  </div>

  <div class="">
    <div class="form-group col-sm-4">
      <%= f.label 'Salary in Lakh Per Annum' %>
      <%= f.text_field :amount , class: 'form-control' %>
    </div>

    <div class="form-group col-sm-4">
      <%= f.label :initial_amount_per_month %>
      <%= f.text_field :initial_amount_per_month ,  class: 'form-control' %>
    </div>

    <div class="form-group col-sm-4">
      <%= f.label 'Provesional period' %>
      <%= f.number_field :prov_period,  class: 'form-control' %>
    </div>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/salaries/edit.html.erb
<div class="container">
  <div class=" jumbotron">
    <div>Editing Salary</div>
    <%= render 'edit_form', salary: @salary %>

    <%= link_to 'Show', @salary %> |
    <%= link_to 'Back', salaries_path %>
  </div>
</div>

app/views/salaries/index.html.erb
<div class="container">
  <div class=" jumbotron">
    <div class="">
      Salaries
        <%= link_to 'New Salary', new_salary_path , class: 'right btn btn-default'%>
    </div>
    <br>
    <table class="table  table-striped table-hover table-condensed">
      <thead>
        <tr>
          <th>Employee Names</th>
          <th>Salary in Lakh Per Annum</th>
          <th>Initial amount per month</th>
          <th>Prov period</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @salaries.each do |salary| %>
          <tr>
            <td><%= salary.user.name %></td>
            <td><%= salary.amount %></td>
            <td><%= salary.initial_amount_per_month %></td>
            <td><%= salary.prov_period %></td>
            <td><%= link_to 'Show', salary %></td>
            <td><%= link_to 'Edit', edit_salary_path(salary) %></td>
            <td><%= link_to 'Destroy', salary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/salaries/new.html.erb
<div class="container">
  <div class=" jumbotron">
    <div>Add Salary for new employee</div>
    <br>
    <%= render 'form', salary: @salary %>
    <%= link_to 'Back', salaries_path %>
  </div>
</div>

app/views/salaries/show.html.erb
<div class="container">
  <div class=" jumbotron">
    <p>
      <strong>Employee Name:</strong>
      <%= @salary.user.name %>
    </p>

    <p>
      <strong>Salary in Lakh Per Annum:</strong>
      <%= @salary.amount %>
    </p>

    <p>
      <strong>Initial amount per month:</strong>
      <%= @salary.initial_amount_per_month %>
    </p>

    <p>
      <strong>Prov period:</strong>
      <%= @salary.prov_period %>
    </p>

    <%= link_to 'Edit', edit_salary_path(@salary) %> |
    <%= link_to 'Back', salaries_path %>
  </div>
</div>