config/routes.rb
Rails.application.routes.draw do
  resources :leave_applications
  resources :invites
  resources :instalments  do
    collection do
      get 'get_instalments'
    end
  end

  resources :documents
  resources :events
  resources :projects
  resources :salary_transactions
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :salaries
  resources :user_profiles
  resources :statuses
  resources :designations
  resources :roles
  devise_for :users
  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :hr do
    collection do
      get 'users'
      get 'get_user_profile'
      post 'invite'
    end
  end

  resources :finance do
    collection do
      get 'salaries'
      get 'check_probation'
      get 'update_probation'
      get 'get_current_salary'
      get 'pay_salary'
    end
  end


  get 'welcome/public/:id', to: 'welcome#public_profile', as: 'public'
  get 'welcome/public_project/:id', to: 'welcome#public_project', as: 'public_project'




end

app/models/instalment.rb
class Instalment < ApplicationRecord
  belongs_to :project
end

app/controllers/instalments_controller.rb
class InstalmentsController < InheritedResources::Base

  before_action :authenticate_user!
  before_action :authorize_d_hr
  before_action :authorize_r_finance

  layout false, only: [ :get_instalments ]

  def get_instalments

    @instalments = Instalment.where(project_id: get_project_params[:project_id]).order(instalment_no:  :asc)

    if   !@instalments.present?
      project = Project.find(get_project_params[:project_id])
      no_instalments = project.no_instalments
      while no_instalments > 0 do
        Instalment.create(project_id: project.id , instalment_no: no_instalments )
        no_instalments = no_instalments - 1
      end
      @instalments = Instalment.where(project_id: get_project_params[:project_id]).order(instalment_no:  :asc)

    end

    respond_to do |format|
      format.html
    end

  end

  def update

    @instalment = Instalment.find(params[:id])
    if @instalment.update(instalment_params)
      respond_to do |format|
            format.js 
      end
    end

  end


  private

  def get_project_params
     params.permit(:project_id)
  end

    def instalment_params
      params.require(:instalment).permit(:project_id, :instalment_date, :amount, :instalment_no)
    end
end

app/helpers/instalments_helper.rb
module InstalmentsHelper
end

app/views/instalments/_form.html.erb
<%= form_for(instalment) do |f| %>
  <% if instalment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instalment.errors.count, "error") %> prohibited this instalment from being saved:</h2>

      <ul>
      <% instalment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %>
    <%= f.text_field :project_id %>
  </div>

  <div class="field">
    <%= f.label :instalment_date %>
    <%= f.date_select :instalment_date %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

  <div class="field">
    <%= f.label :instalment_no %>
    <%= f.number_field :instalment_no %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instalments/edit.html.erb
<h1>Editing Instalment</h1>

<%= render 'form', instalment: @instalment %>

<%= link_to 'Show', @instalment %> |
<%= link_to 'Back', instalments_path %>

app/views/instalments/get_instalments.html.erb
<div class="jumbotron">


    <% @instalments.each do |instalment| %>

        <%= form_for(instalment , :html=>{:multipart => true,:remote=>true} ) do |f| %>
          <% if instalment.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(instalment.errors.count, "error") %> prohibited this instalment from being saved:</h2>

              <ul>
              <% instalment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="row">
            <%= f.hidden_field :project_id  , class: "col-sm-1"%>
            <%= f.hidden_field :instalment_no , class: "col-sm-1" %>

            <div class="">
              Instalment No : <%= f.label instalment.instalment_no %>
            </div>
            <div class="form-group">
              <%= f.label :amount %>
              <%= f.text_field :amount  , class: "form-control" %>
            </div>
            <div class="">
              <%= f.label :instalment_date %>
              <br>
              <%= f.date_select(:instalment_date, {}, {:class => "form-control col-sm-3 frm-date"}) %>
            </div>

            <%= f.submit  "Update" , class: "update_instalment" %>
            </div>
        <% end %>
        <br>

    <% end %>
</div>

<script type="text/javascript">
  $('.update_instalment').closest('form').on('ajax:success', function() {
    alert("Successfully Updated");
  });

</script>

app/views/instalments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Instalments</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Instalment date</th>
      <th>Amount</th>
      <th>Instalment no</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instalments.each do |instalment| %>
      <tr>
        <td><%= instalment.project %></td>
        <td><%= instalment.instalment_date %></td>
        <td><%= instalment.amount %></td>
        <td><%= instalment.instalment_no %></td>
        <td><%= link_to 'Show', instalment %></td>
        <td><%= link_to 'Edit', edit_instalment_path(instalment) %></td>
        <td><%= link_to 'Destroy', instalment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instalment', new_instalment_path %>

app/views/instalments/new.html.erb
<h1>New Instalment</h1>

<%= render 'form', instalment: @instalment %>

<%= link_to 'Back', instalments_path %>

app/views/instalments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @instalment.project %>
</p>

<p>
  <strong>Instalment date:</strong>
  <%= @instalment.instalment_date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @instalment.amount %>
</p>

<p>
  <strong>Instalment no:</strong>
  <%= @instalment.instalment_no %>
</p>

<%= link_to 'Edit', edit_instalment_path(@instalment) %> |
<%= link_to 'Back', instalments_path %>